/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false server/worker-configuration.d.ts` (hash: 0b0dd6af926b1aa8aaaca8bd5d353f95)
interface __BaseEnv_Env {
  DB: D1Database;
  SYNC_QUEUE: Queue;
  SYNC_FETCH_LIMIT: "100";
  SYNC_TIMEOUT_MS: "480000";
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "SYNC_FETCH_LIMIT" | "SYNC_TIMEOUT_MS">
  > {}
}
