/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=GeneratedEnv server/worker-configuration.d.ts` (hash: 43752c276148021b019433e04141708a)
interface __BaseEnv_GeneratedEnv {
  DB: D1Database;
  SYNC_QUEUE: Queue;
  SYNC_FETCH_LIMIT: "100";
  SYNC_TIMEOUT_MS: "480000";
  PRODUCTION_DEBUG: "false";
  CREDENTIAL_ENCRYPTION_KEY: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  MICROSOFT_CLIENT_ID: string;
  MICROSOFT_CLIENT_SECRET: string;
  VAPID_PUBLIC_KEY: string;
  VAPID_PRIVATE_KEY: string;
  VAPID_SUBJECT: string;
  ACCESS_JWKS: string;
  ACCESS_AUD: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_GeneratedEnv {}
}
interface GeneratedEnv extends __BaseEnv_GeneratedEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "SYNC_FETCH_LIMIT"
      | "SYNC_TIMEOUT_MS"
      | "PRODUCTION_DEBUG"
      | "CREDENTIAL_ENCRYPTION_KEY"
      | "GOOGLE_CLIENT_ID"
      | "GOOGLE_CLIENT_SECRET"
      | "MICROSOFT_CLIENT_ID"
      | "MICROSOFT_CLIENT_SECRET"
      | "VAPID_PUBLIC_KEY"
      | "VAPID_PRIVATE_KEY"
      | "VAPID_SUBJECT"
      | "ACCESS_JWKS"
      | "ACCESS_AUD"
    >
  > {}
}
